---
version: 2
models:
- name: "model_testing1_dynamic_select_city_data"
  tags:
  - "prophecy_temp"
sources:
- name: "prophecy__temp_testing1_source"
  database: "pipelinehub"
  schema: "katherine"
  tags:
  - "prophecy_temp"
  config:
    enabled: true
  tables:
  - name: "prophecy__temp_testing1_post_dynamic_select_city_data_0"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_testing1_pre_dynamic_select_city_data_0"
    tags:
    - "prophecy_temp"
